"""A minimal Freeciv 3.2.5 network client that controls one player, so an
external policy can issue *genuine* production, research and unit decisions —
the ones server-side Lua cannot express. Speaks the real wire protocol (see
civharness.proto).

Lifecycle for a branch:
    1. The server loads a savegame and stays in pregame (no `start` yet),
       with `set timeout 0` (wait for players, no wall clock) and
       `set autotoggle enabled` (AI drops off a player when we take it).
    2. connect() logs in; take(name) grabs the focal player; start() begins.
    3. run(on_phase) drives the game: on every START_PHASE the callback issues
       orders, then we send PLAYER_PHASE_DONE for the exact current turn
       (a mismatched turn is silently dropped by the server) and the turn
       advances only on our cue — which is what keeps the branch deterministic.

Rule names -> numeric ids come from RuleIds, populated by a one-shot Lua dump
(find.unit_type / building_type / tech_type + :rule_name) parsed out of the
server log — ruleset-agnostic, no fragile ruleset-packet decoding.
"""

import socket
import time
from dataclasses import dataclass, field
from pathlib import Path

from civharness.playerview import PlayerViewCache
from civharness.proto import packets as P
from civharness.proto.framing import PacketFraming, ProtocolError
from civharness.proto.rulesets import RulesetCatalog


class ControlLost(RuntimeError):
    """A controlling client stopped driving its player before the game ended —
    a dropped connection or a phase that never arrived. With `autotoggle
    enabled` the server's AI silently retakes the abandoned seat and finishes
    the game, so any trajectory continued past this point would be falsely
    reported as agent-controlled. Drivers must raise this instead of continuing.

    The message starts with the loss class — ``GAME:`` (the player is out of
    the game), ``INFRA:`` (the seat stalled while the player was alive) or
    ``UNKNOWN:`` — see civharness.branch.classify_control_loss. The same class
    is available as `kind`.
    """

    kind: str = "UNKNOWN"


class LegalActionsUnavailable(RuntimeError):
    """A `get_unit_actions` query received no UNIT_ACTIONS reply before its
    timeout (the connection stalled or dropped). Kept distinct from an empty
    result — an empty dict means the server *answered* and the unit has no legal
    action against that target, whereas this means the question was never
    answered."""


# Lua that dumps id<->rule_name for the three families we resolve. Loaded via
# `lua file` before `start`; its CIVHARNESS log lines feed RuleIds.from_log.
RULE_DUMP_LUA = """-- generated by civharness.client — id<->rule_name dump
local function dump(kind, finder)
  local id = 0
  while true do
    local obj = finder(id)
    if not obj then break end
    log.normal("CIVHARNESS " .. kind .. " " .. id .. " " .. obj:rule_name())
    id = id + 1
  end
end
dump("utype", function(i) return find.unit_type(i) end)
dump("impr", function(i) return find.building_type(i) end)
dump("tech", function(i) return find.tech_type(i) end)
dump("govt", function(i) return find.government(i) end)
dump("action", function(i) return find.action(i) end)
dump("terrain", function(i) return find.terrain(i) end)
-- Freeciv builds that expose extras to Lua populate this optional family.
-- Guard it so older/minimal Lua APIs still complete the rule dump.
dump("extra", function(i)
  if find.extra then return find.extra(i) end
  return nil
end)
log.normal("CIVHARNESS dump_done")
"""


@dataclass
class RuleIds:
    """rule_name -> numeric id, per family, read from the server's Lua dump."""

    units: dict[str, int] = field(default_factory=dict)
    improvements: dict[str, int] = field(default_factory=dict)
    techs: dict[str, int] = field(default_factory=dict)
    governments: dict[str, int] = field(default_factory=dict)
    actions: dict[str, int] = field(default_factory=dict)
    extras: dict[str, int] = field(default_factory=dict)
    terrains: dict[str, int] = field(default_factory=dict)

    @classmethod
    def from_log(cls, log_path: Path) -> "RuleIds":
        r = cls()
        table = {
            "utype": r.units,
            "impr": r.improvements,
            "tech": r.techs,
            "govt": r.governments,
            "action": r.actions,
            "extra": r.extras,
            "terrain": r.terrains,
        }
        for line in Path(log_path).read_text(errors="replace").splitlines():
            if "CIVHARNESS " not in line:
                continue
            parts = line.split("CIVHARNESS ", 1)[1].split(None, 2)
            if len(parts) == 3 and parts[0] in table:
                table[parts[0]][parts[2]] = int(parts[1])
        return r

    @property
    def ready(self) -> bool:
        return bool(self.units and self.improvements and self.techs)


class FreecivClient:
    """One logged-in connection controlling one player (see module docstring)."""

    def __init__(self, host: str, port: int, username: str = "civharness"):
        self.host = host
        self.port = port
        self.username = username
        self.sock: socket.socket | None = None
        self.fr: PacketFraming | None = None
        self.enc = P.DeltaEncoder()
        self.conn_id: int | None = None
        self.turn: int | None = None  # last turn seen via NEW_YEAR
        self.rules: RuleIds | None = None
        self.over = False  # set once PACKET_ENDGAME_REPORT is seen
        self._closed = False
        self._last_unit_actions = None  # delta baseline for UNIT_ACTIONS replies
        # The incremental player-scoped view actually delivered to THIS
        # connection (fog of war as the server computed it) — never derived
        # from the omniscient autosave.
        self.view = PlayerViewCache()
        # Extras/actions ruleset catalogs from the login burst — the only
        # source of extra ids + action sub-target kinds on 3.2.5 (no Lua
        # find.extra in this version).
        self.rulesets = RulesetCatalog()

    # -- connection / login -------------------------------------------------
    def connect(self, timeout: float = 15.0) -> dict:
        self.view.reset()  # a (re)connect restarts the server's delta stream
        self.rulesets.reset()
        self.sock = socket.create_connection((self.host, self.port), timeout=timeout)
        self.fr = PacketFraming(self.sock)
        self.fr.send(P.SERVER_JOIN_REQ, P.server_join_req(self.username))
        while True:
            ptype, body = self.fr.next_packet(timeout=timeout)
            if ptype == P.SERVER_JOIN_REPLY:
                reply = P.decode_join_reply(body)
                if not reply["you_can_join"]:
                    raise ProtocolError(f"server refused join: {reply['message']}")
                self.conn_id = reply["conn_id"]
                self.fr.login_header = False  # header flips after JOIN_REPLY
                return reply

    def _handle(self, ptype: int, body: bytes) -> None:
        """React to the packets we care about: keep-alive, turn tracking, the
        per-connection player-view cache and the ruleset catalog."""
        if ptype == P.CONN_PING:
            self.fr.send(P.CONN_PONG, P.empty())
        elif ptype == P.NEW_YEAR:
            t = P.decode_new_year(body)
            if t is not None:
                self.turn = t
        elif self.view.handles(ptype):
            self.view.feed(ptype, body)
        elif self.rulesets.handles(ptype):
            self.rulesets.feed(ptype, body)

    def pump(self, seconds: float) -> None:
        """Read and dispatch whatever arrives for a bounded window."""
        end = time.time() + seconds
        while time.time() < end:
            try:
                ptype, body = self.fr.next_packet(timeout=max(0.05, end - time.time()))
            except (ProtocolError, TimeoutError):
                break
            self._handle(ptype, body)

    # -- server commands (chat) ---------------------------------------------
    def command(self, text: str) -> None:
        """Issue a server command as a chat message (e.g. '/take \"Name\"')."""
        self.fr.send(P.CHAT_MSG_REQ, self.enc.encode(P.CHAT_MSG_REQ, [text]))

    def take(self, player_name: str) -> None:
        self.command(f'/take "{player_name}"')

    def start(self) -> None:
        self.command("/start")

    # -- control: construction ----------------------------------------------
    def set_production(self, city_id: int, kind: int, value: int) -> None:
        """kind = P.VUT_UTYPE (unit) or P.VUT_IMPROVEMENT (building)."""
        self.fr.send(
            P.CITY_CHANGE, self.enc.encode(P.CITY_CHANGE, [city_id, kind, value])
        )

    def build_unit(self, city_id: int, unit_name: str) -> None:
        self.set_production(city_id, P.VUT_UTYPE, self.rules.units[unit_name])

    def build_improvement(self, city_id: int, impr_name: str) -> None:
        self.set_production(
            city_id, P.VUT_IMPROVEMENT, self.rules.improvements[impr_name]
        )

    def set_worklist(self, city_id: int, entries: list[tuple[str, str]]) -> None:
        """entries: [("unit"|"building", rule_name), ...] — the city's build
        queue after its current target."""
        wl = []
        for kind, name in entries:
            if kind == "unit":
                wl.append((P.VUT_UTYPE, self.rules.units[name]))
            elif kind == "building":
                wl.append((P.VUT_IMPROVEMENT, self.rules.improvements[name]))
            else:
                raise ValueError(f"worklist kind must be unit|building, got {kind!r}")
        self.fr.send(P.CITY_WORKLIST, self.enc.encode(P.CITY_WORKLIST, [city_id, wl]))

    def buy(self, city_id: int) -> None:
        """Rush-buy the city's current production."""
        self.fr.send(P.CITY_BUY, self.enc.encode(P.CITY_BUY, [city_id]))

    def sell(self, city_id: int, impr_name: str) -> None:
        bid = self.rules.improvements[impr_name]
        self.fr.send(P.CITY_SELL, self.enc.encode(P.CITY_SELL, [city_id, bid]))

    def change_specialist(self, city_id: int, from_sp: int, to_sp: int) -> None:
        self.fr.send(
            P.CITY_CHANGE_SPECIALIST,
            self.enc.encode(P.CITY_CHANGE_SPECIALIST, [city_id, from_sp, to_sp]),
        )

    # -- control: research --------------------------------------------------
    def set_research(self, tech_name: str) -> None:
        self.fr.send(
            P.PLAYER_RESEARCH,
            self.enc.encode(P.PLAYER_RESEARCH, [self.rules.techs[tech_name]]),
        )

    def set_tech_goal(self, tech_name: str) -> None:
        self.fr.send(
            P.PLAYER_TECH_GOAL,
            self.enc.encode(P.PLAYER_TECH_GOAL, [self.rules.techs[tech_name]]),
        )

    def set_research_id(self, tech_id: int) -> None:
        self.fr.send(P.PLAYER_RESEARCH, self.enc.encode(P.PLAYER_RESEARCH, [tech_id]))

    def set_tech_goal_id(self, tech_id: int) -> None:
        self.fr.send(P.PLAYER_TECH_GOAL, self.enc.encode(P.PLAYER_TECH_GOAL, [tech_id]))

    # -- control: unit orders (low-level; goto/activities) ------------------
    def unit_orders(
        self,
        unit_id: int,
        src_tile: int,
        orders: list[dict],
        dest_tile: int,
        repeat: bool = False,
        vigilant: bool = False,
    ) -> None:
        self.fr.send(
            P.UNIT_ORDERS,
            self.enc.encode_unit_orders(
                unit_id, src_tile, orders, dest_tile, repeat, vigilant
            ),
        )

    # -- control: rates / government / worked tiles -------------------------
    def set_rates(self, tax: int, luxury: int, science: int) -> None:
        """Set tax/luxury/science percents (PACKET_PLAYER_RATES). The engine
        clamps to the government's max rate and requires a valid split."""
        self.fr.send(
            P.PLAYER_RATES, self.enc.encode(P.PLAYER_RATES, [tax, luxury, science])
        )

    def change_government(self, gov_name: str) -> None:
        """Switch government (PACKET_PLAYER_CHANGE_GOVERNMENT); may trigger
        anarchy per the ruleset."""
        self.fr.send(
            P.PLAYER_CHANGE_GOVERNMENT,
            self.enc.encode(
                P.PLAYER_CHANGE_GOVERNMENT, [self.rules.governments[gov_name]]
            ),
        )

    def make_worker(self, city_id: int, tile: int) -> None:
        """Put a citizen to work `tile` (packed index y*xsize + x)."""
        self.fr.send(
            P.CITY_MAKE_WORKER, self.enc.encode(P.CITY_MAKE_WORKER, [city_id, tile])
        )

    def make_specialist(self, city_id: int, tile: int) -> None:
        """Pull the worker off `tile` into a specialist (packed tile index)."""
        self.fr.send(
            P.CITY_MAKE_SPECIALIST,
            self.enc.encode(P.CITY_MAKE_SPECIALIST, [city_id, tile]),
        )

    # -- control: diplomacy (declare war / cancel a pact) -------------------
    def cancel_pact(self, other_player_id: int, clause: int = P.CLAUSE_PEACE) -> None:
        """PACKET_DIPLOMACY_CANCEL_PACT: step the diplomatic state with
        `other_player_id` down one level (the server ignores the specific clause
        except VISION/SHARED_TILES)."""
        self.fr.send(
            P.DIPLOMACY_CANCEL_PACT,
            self.enc.encode(P.DIPLOMACY_CANCEL_PACT, [other_player_id, clause]),
        )

    def declare_war(self, other_player_id: int, steps: int = 2) -> None:
        """Reach war by cancelling the pact repeatedly — each cancel steps down
        one level, so peace -> war can take two (peace -> armistice -> war)."""
        for _ in range(max(1, steps)):
            self.cancel_pact(other_player_id, P.CLAUSE_PEACE)

    # -- legal-action discovery (what can this unit do?) --------------------
    def get_unit_actions(
        self,
        actor_unit_id: int,
        target_tile: int = -1,
        target_unit: int = 0,
        target_extra: int = -1,
        request_kind: int = 1,
        timeout: float = 5.0,
    ) -> dict[str, tuple[int, int]]:
        """Ask the server which actions `actor_unit_id` may take against a target
        (PACKET_UNIT_GET_ACTIONS -> PACKET_UNIT_ACTIONS). Returns
        {action_rule_name: (min_prob, max_prob)} for the actions that are
        possible (the (0,0) impossible sentinel is dropped). Names resolve via
        the Lua action dump; unmapped ids fall back to 'action_<id>'.

        An empty dict is a real answer: the server replied and the unit has no
        legal action against that target. If no reply arrives before `timeout`
        (a stalled/dropped connection), `LegalActionsUnavailable` is raised so
        the caller can tell "nothing legal" from "never answered"."""
        self.fr.send(
            P.UNIT_GET_ACTIONS,
            self.enc.encode(
                P.UNIT_GET_ACTIONS,
                [actor_unit_id, target_unit, target_tile, target_extra, request_kind],
            ),
        )
        deadline = time.time() + timeout
        while time.time() < deadline:
            try:
                ptype, body = self.fr.next_packet(
                    timeout=min(1.0, deadline - time.time())
                )
            except TimeoutError:
                continue  # just an idle read — keep waiting until the FULL deadline
            except ProtocolError:
                break  # a real disconnect — stop immediately
            if ptype == P.UNIT_ACTIONS:
                self._last_unit_actions = P.decode_unit_actions(
                    body, self._last_unit_actions
                )
                ua = self._last_unit_actions
                if ua["actor_unit_id"] == actor_unit_id:
                    return self._legal_from_probs(ua["action_probabilities"])
            else:
                self._handle(ptype, body)
        raise LegalActionsUnavailable(
            f"no UNIT_ACTIONS reply for unit {actor_unit_id} within {timeout:.0f}s "
            f"(connection stalled or dropped) — not the same as 'no legal actions'"
        )

    def _legal_from_probs(self, probs) -> dict[str, tuple[int, int]]:
        id2name = {v: k for k, v in (self.rules.actions or {}).items()}
        out = {}
        for aid, pair in enumerate(probs):
            if tuple(pair) == (0, 0):  # impossible / not applicable
                continue
            out[id2name.get(aid, f"action_{aid}")] = tuple(pair)
        return out

    def do_action(
        self,
        actor_unit_id: int,
        action,
        target_id: int | None = None,
        sub_target: int = 0,
        name: str = "",
    ) -> None:
        """Perform a unit action by rule name (PACKET_UNIT_DO_ACTION) — the
        executable counterpart to get_unit_actions' discovery. `action` is a rule
        name (e.g. "Fortify", "Disband Unit", "Build Irrigation") resolved via the
        action dump, or a raw action id.

        `target_id` defaults to the actor's own unit id — correct for self/unit
        actions; pass a **tile index** (y*xsize + x) for tile actions or a city
        id for city actions. `sub_target` is the extra or building id when the
        action needs one (0 = none; -1 lets the server pick, but only for a
        *flexible* action — a mandatory one like Build Irrigation must be given
        the extra id). The server performs the action from this single packet;
        no follow-up is needed. Legality is the caller's to establish (ask
        get_unit_actions first)."""
        aid = action if isinstance(action, int) else self.rules.actions[action]
        if target_id is None:
            target_id = actor_unit_id
        self.fr.send(
            P.UNIT_DO_ACTION,
            self.enc.encode(
                P.UNIT_DO_ACTION, [actor_unit_id, target_id, sub_target, name, aid]
            ),
        )

    # -- turn pacing --------------------------------------------------------
    def phase_done(self) -> None:
        """End our phase for the current turn (advances the game on our cue)."""
        self.fr.send(
            P.PLAYER_PHASE_DONE, self.enc.encode(P.PLAYER_PHASE_DONE, [self.turn or 0])
        )

    def next_phase(self, max_seconds: float = 600.0) -> int | None:
        """Pump packets until our next START_PHASE, returning its turn number.
        Returns None if the game ended (sets `self.over`), the connection
        dropped, or max_seconds elapsed. Keep-alive and turn tracking happen
        along the way. This is the primitive both run() and the multi-agent
        driver step on."""
        deadline = time.time() + max_seconds
        while time.time() < deadline:
            try:
                ptype, body = self.fr.next_packet(
                    timeout=min(5.0, deadline - time.time())
                )
            except ProtocolError:
                self._closed = True
                return None  # connection dropped
            except TimeoutError:
                continue
            self._handle(ptype, body)
            if ptype == P.ENDGAME_REPORT:
                self.over = True  # game over, even if we were eliminated
                return None
            if ptype == P.START_PHASE:
                return self.turn
        return None

    def run(self, on_phase=None, max_seconds: float = 600.0) -> bool:
        """Drive the game to its end. `on_phase(self, turn)` is invoked once per
        START_PHASE to issue that turn's orders; we then send PHASE_DONE. The
        game advances only on our PHASE_DONE (timeout 0). Returns True when the
        server signals game over — after which the caller must close() so the
        server, held open until every client logs out (srv_main.c S_S_OVER
        loop), can finally exit. Returns False if the connection dropped or
        max_seconds elapsed first."""
        deadline = time.time() + max_seconds
        while True:
            remaining = deadline - time.time()
            if remaining <= 0:
                return False
            turn = self.next_phase(max_seconds=remaining)
            if turn is None:
                return self.over
            if on_phase is not None:
                on_phase(self, turn)
            self.phase_done()

    @property
    def dropped(self) -> bool:
        """True once the socket closed unexpectedly (a `ProtocolError` in
        next_phase/pump) — as opposed to a clean game-over (`self.over`)."""
        return self._closed

    def close(self) -> None:
        if self.sock is not None and not self._closed:
            try:
                # Drain before closing: at game end the server pushes a large
                # endgame burst (full-map reveal) to every client. Closing
                # with that data unread can block the server's send buffer
                # until its ~60s "lagging connection" detector fires — with
                # several clients that serial wait exceeds the drive timeout.
                # Signal we're done writing, then consume until EOF (bounded)
                # so the server sees a clean disconnect immediately.
                self.sock.shutdown(socket.SHUT_WR)
                self.sock.settimeout(0.5)
                for _ in range(20000):  # bounded: ~a few MB of endgame data
                    if not self.sock.recv(65536):
                        break
            except OSError:
                pass
            try:
                self.sock.close()
            except OSError:
                pass
            self._closed = True
